### ISSUE TITLE
Progress bar looping animation got on top of the off-canvas

### ISSUE THREAD

**Issue by Qu1etboy** [Qu1etboy/bangkok-air-quality-map#1]
## Description
Progress bar looping animation got on top of the off-canvas. This problem happens only if CSS animation is applied

at `Header.tsx` if you remove `animate-progress` class, everything will work fine. however, I want a cool loading animation but don't know how to fix it. Help would be appreciated

```ts
<div className="h-1 w-full overflow-hidden bg-gray-200">
  <div className="animate-progress h-full bg-gradient-to-r from-green-500 to-green-700"></div>
</div>
```

## Screenshot
<img width="1412" alt="Screen Shot 2566-04-08 at 03 22 26" src="https://user-images.githubusercontent.com/95042765/230674229-225a48e8-e2f5-4301-b217-cf13f2ef95f5.png">

**Comment by bernco** [comment]
Hi, I think probably the problem could be from the stacking of your elements.
you can use a higher z-index in the off-canvas element by adding a CSS rule.

```
.off-canvas {
  z-index: 1000;
}

```
